# github action to choose environment and deploy
name: Deploy

#on user input
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Version to deploy'
        required: true
        default: 'latest'
      choice:
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - test
          - prod
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        #directory is root of the project
        working-directory: .
    steps:
      # checkout the code
      - name: Checkout
        uses: actions/checkout@v2
          # display current directory
      - name: Display working directory
        run: pwd
          # print current branch
      - name: Print current branch
        run: echo $GITHUB_REF
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Get git notes from latest tag
        id: get_notes
        uses:
          fregante/get-tagged-commits@v1
        with:
          tag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print notes
        run: echo ${{ steps.get_notes.outputs.notes }}
